require("plugins.config.nvim-lspconfig.cssls")
require("plugins.config.nvim-lspconfig.emmet_language_server")
require("plugins.config.nvim-lspconfig.gopls")
require("plugins.config.nvim-lspconfig.java_language_server")
require("plugins.config.nvim-lspconfig.lua_ls")
require("plugins.config.nvim-lspconfig.svelte")
require("plugins.config.nvim-lspconfig.ts_ls")

vim.lsp.enable("cssls")
vim.lsp.enable("emmet_language_server")
vim.lsp.enable("gopls")
vim.lsp.enable("java_language_server")
vim.lsp.enable("lua_ls")
vim.lsp.enable("svelte")
vim.lsp.enable("ts_ls")
